version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8090:8090
#    expose:
#      - 8090
#    environment:
#      - VIRTUAL_HOST=http://localhost
#      - VIRTUAL_PORT=8090
#      - LETSENCRYPT_HOST=http://localhost
#      - LETSENCRYPT_EMAIL=myemail@mydomain.com
    networks:
      - reverse-proxy
    restart: always


networks:
  backend:
  reverse-proxy:
    external:
      name: reverse-proxy